openapi: 3.0.3
info:
  title: IoT SIM Fraud Prevention Subscriptions API
  description: |
    This API allows customers to subscribe to notifications when SIM card bindings change.

    **Event Types & Schema References:**
    - `IMEI_CHANGE`: Event schema defined as `ImeiChangeEventData` (see components/schemas)
    - `AREA_CHANGE`: Event schema defined as `AreaChangeEventData` (see components/schemas)

    **CloudEvents Compliance:**
    - All events conform to CloudEvents v1.0 specification
    - Event types use CAMARA canonical URIs:
      * `org.camara.iot-sim-fraud-prevention.v1.imei-changed`
      * `org.camara.iot-sim-fraud-prevention.v1.area-changed`
    - `data` field strictly follows schemas defined in this specification

    **Event Payload Structure (CloudEvents):**
    ```json
    {
      "id": "evt_9d8e7f6a",
      "source": "https://api.camara.org/iot-sim-fraud-prevention",
      "type": "org.camara.iot-sim-fraud-prevention.v1.imei-changed",
      "specversion": "1.0",
      "datacontenttype": "application/json",
      "time": "2023-08-15T14:22:18.312Z",
      "data": { /* Strictly validated against ImeiChangeEventData schema */ }
    }
    ```

    Full schema definitions available in components/schemas section below.
  version: 1.0.0
  contact:
    name: CAMARA API Support
    url: https://camara.org/support
    email: api-support@camara.org
  license:
    name: CAMARA API License
    url: https://camara.org/license

servers:
  - url: https://api.{environment}.camara.org/iot-sim-fraud-prevention-subscription/v1
    description: CAMARA IoT SIM Fraud Prevention Subscriptions API
    variables:
      environment:
        default: production
        enum: [sandbox, production]
        description: Environment selector

paths:
  /subscriptions:
    post:
      summary: Create a new subscription
      operationId: createSubscription
      description: |
        Creates a subscription to binding change events.
        Only one active subscription per event type per SIM is allowed.
        New subscription of same type replaces existing one.
      tags: [Subscriptions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionCreateRequest'
            examples:
              imeiChangeSubscription:
                summary: Subscribe to IMEI change events
                value:
                  eventType: "IMEI_CHANGE"
                  sink: "https://api.example.com/fraud-notifications"
                  config:
                    subscriptionExpireTime: "2024-12-31T23:59:59Z"
                    subscriptionMaxEvents: 100
              areaChangeSubscription:
                summary: Subscribe to area change events
                value:
                  eventType: "AREA_CHANGE"
                  sink: "https://api.example.com/fraud-notifications"
                  config:
                    initialEvent: true
      responses:
        '201':
          description: Subscription created successfully
          headers:
            Location:
              description: URI of the newly created subscription resource
              schema:
                type: string
                format: uri
                example: /subscriptions/sub_3c4d5e6f
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              examples:
                subscriptionCreated:
                  summary: Subscription created
                  value:
                    id: "sub_3c4d5e6f"
                    eventType: "IMEI_CHANGE"
                    sink: "https://api.example.com/fraud-notifications"
                    status: "ACTIVE"
                    config:
                      subscriptionExpireTime: "2024-12-31T23:59:59Z"
                      subscriptionMaxEvents: 100
                    createdAt: "2023-08-15T10:30:00Z"
                    updatedAt: "2023-08-15T10:30:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'

    get:
      summary: List all subscriptions for the authenticated SIM
      operationId: listSubscriptions
      description: |
        Retrieves all subscriptions (active and inactive) for the SIM card associated with the access token.

        **Filtering:**
        - Use `eventType` query parameter to filter by event type
        - Omit parameter to retrieve all subscriptions
      tags: [Subscriptions]
      parameters:
        - name: eventType
          in: query
          description: Filter subscriptions by event type
          required: false
          schema:
            type: string
            enum: [IMEI_CHANGE, AREA_CHANGE]
          example: "IMEI_CHANGE"
      responses:
        '200':
          description: List of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
              examples:
                allSubscriptions:
                  summary: All subscriptions for SIM
                  value:
                    - id: "sub_3c4d5e6f"
                      eventType: "IMEI_CHANGE"
                      sink: "https://api.example.com/fraud-notifications"
                      status: "ACTIVE"
                      config:
                        subscriptionExpireTime: "2024-12-31T23:59:59Z"
                        subscriptionMaxEvents: 100
                      createdAt: "2023-08-15T10:30:00Z"
                      updatedAt: "2023-08-15T10:30:00Z"
                    - id: "sub_7g8h9i0j"
                      eventType: "AREA_CHANGE"
                      sink: "https://api.example.com/fraud-notifications"
                      status: "INACTIVE"
                      endedReason: "SUBSCRIPTION_EXPIRED"
                      config:
                        subscriptionExpireTime: "2023-08-10T23:59:59Z"
                      createdAt: "2023-07-01T09:15:00Z"
                      updatedAt: "2023-08-10T23:59:59Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /subscriptions/{subscriptionId}:
    get:
      summary: Get subscription details
      operationId: getSubscription
      description: Retrieves details of a specific subscription resource
      tags: [Subscriptions]
      parameters:
        - name: subscriptionId
          in: path
          required: true
          description: Unique identifier of the subscription resource
          schema:
            type: string
            pattern: '^sub_[a-zA-Z0-9]{8,32}$'
          example: "sub_3c4d5e6f"
      responses:
        '200':
          description: Subscription details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              examples:
                activeSubscription:
                  summary: Active subscription details
                  value:
                    id: "sub_3c4d5e6f"
                    eventType: "IMEI_CHANGE"
                    sink: "https://api.example.com/fraud-notifications"
                    status: "ACTIVE"
                    config:
                      subscriptionExpireTime: "2024-12-31T23:59:59Z"
                      subscriptionMaxEvents: 100
                    createdAt: "2023-08-15T10:30:00Z"
                    updatedAt: "2023-08-15T10:30:00Z"
                inactiveSubscription:
                  summary: Inactive subscription details
                  value:
                    id: "sub_7g8h9i0j"
                    eventType: "AREA_CHANGE"
                    sink: "https://api.example.com/fraud-notifications"
                    status: "INACTIVE"
                    endedReason: "SUBSCRIPTION_EXPIRED"
                    config:
                      subscriptionExpireTime: "2023-08-10T23:59:59Z"
                    createdAt: "2023-07-01T09:15:00Z"
                    updatedAt: "2023-08-10T23:59:59Z"
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a subscription
      operationId: deleteSubscription
      description: |
        Deletes a subscription, stopping future notifications.

        **Behavior:**
        - Subscription status changes to `INACTIVE`
        - `endedReason` is set to `SUBSCRIPTION_DELETED`
        - Resource remains queryable for audit purposes
        - No notifications will be sent after deletion
      tags: [Subscriptions]
      parameters:
        - name: subscriptionId
          in: path
          required: true
          description: Unique identifier of the subscription to delete
          schema:
            type: string
            pattern: '^sub_[a-zA-Z0-9]{8,32}$'
          example: "sub_3c4d5e6f"
      responses:
        '204':
          description: Subscription deleted successfully (no content)
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    # ========== 事件负载 Schema (CloudEvents data field) ==========
    Point:
      type: object
      required: [latitude, longitude]
      description: Geographic coordinate using WGS84 datum
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          description: Latitude coordinate in decimal degrees
          example: 40.7128
        longitude:
          type: number
          minimum: -180
          maximum: 180
          description: Longitude coordinate in decimal degrees
          example: -74.006

    ImeiChangeEventData:
      type: object
      required: [subscriptionId, previousImei, newImei, timestamp]
      description: Data payload for IMEI_CHANGE events (CloudEvents data field)
      properties:
        subscriptionId:
          type: string
          pattern: '^sub_[a-zA-Z0-9]{8,32}$'
          description: ID of the subscription that triggered this event
          example: "sub_3c4d5e6f"
        previousImei:
          type: string
          pattern: '^\d{15}$'
          description: IMEI value before the change
          example: "356938035643809"
        newImei:
          type: string
          pattern: '^\d{15}$'
          description: IMEI value after the change
          example: "356938035643810"
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the IMEI change was detected (RFC 3339)
          example: "2023-08-15T14:22:15Z"

    AreaBindingDataForEvent:
      type: object
      required: [areaType, center, radius]
      description: Area definition used in event payloads
      properties:
        areaType:
          type: string
          enum: [CIRCLE]
          description: Type of area geometry
          example: "CIRCLE"
        center:
          $ref: '#/components/schemas/Point'
        radius:
          type: integer
          minimum: 100
          maximum: 200000
          description: Radius of the area in meters
          example: 5000

    AreaChangeEventData:
      type: object
      required: [subscriptionId, previousArea, newArea, timestamp]
      description: Data payload for AREA_CHANGE events (CloudEvents data field)
      properties:
        subscriptionId:
          type: string
          pattern: '^sub_[a-zA-Z0-9]{8,32}$'
          description: ID of the subscription that triggered this event
          example: "sub_7g8h9i0j"
        previousArea:
          $ref: '#/components/schemas/AreaBindingDataForEvent'
          description: Area definition before the change
        newArea:
          $ref: '#/components/schemas/AreaBindingDataForEvent'
          description: Area definition after the change
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the area change was detected (RFC 3339)
          example: "2023-08-15T15:30:42Z"

    # ========== 订阅资源 Schema ==========
    Subscription:
      type: object
      required: [id, eventType, sink, status, createdAt, updatedAt]
      properties:
        id:
          type: string
          pattern: '^sub_[a-zA-Z0-9]{8,32}$'
          description: Unique identifier for the subscription resource
          example: "sub_3c4d5e6f"
        eventType:
          type: string
          enum: [IMEI_CHANGE, AREA_CHANGE]
          description: Type of event to subscribe to
          example: "IMEI_CHANGE"
        sink:
          type: string
          format: uri
          description: HTTPS endpoint where notifications will be delivered
          example: "https://api.example.com/fraud-notifications"
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
          description: Current status of the subscription
          example: "ACTIVE"
        endedReason:
          type: string
          enum: [SUBSCRIPTION_EXPIRED, MAX_EVENTS_REACHED, ACCESS_TOKEN_EXPIRED, SUBSCRIPTION_DELETED]
          description: Reason why subscription became inactive (only present when status is INACTIVE)
          example: "SUBSCRIPTION_EXPIRED"
        config:
          $ref: '#/components/schemas/SubscriptionConfig'
        createdAt:
          type: string
          format: date-time
          description: Timestamp when subscription was created (RFC 3339)
          example: "2023-08-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when subscription was last updated (RFC 3339)
          example: "2023-08-15T10:30:00Z"

    SubscriptionCreateRequest:
      type: object
      required: [eventType, sink]
      properties:
        eventType:
          type: string
          enum: [IMEI_CHANGE, AREA_CHANGE]
          description: Type of event to subscribe to
        sink:
          type: string
          format: uri
          description: HTTPS endpoint where notifications will be delivered
          example: "https://api.example.com/fraud-notifications"
        config:
          $ref: '#/components/schemas/SubscriptionConfig'

    SubscriptionConfig:
      type: object
      description: Optional configuration parameters for the subscription
      properties:
        initialEvent:
          type: boolean
          description: Whether to send an initial event immediately upon subscription creation
          default: false
          example: true
        subscriptionMaxEvents:
          type: integer
          minimum: 1
          description: Maximum number of events to deliver before automatically terminating subscription
          example: 100
        subscriptionExpireTime:
          type: string
          format: date-time
          description: Timestamp when subscription should automatically expire (RFC 3339)
          example: "2024-12-31T23:59:59Z"

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          description: Machine-readable error code
          example: "INVALID_SINK_URL"
        message:
          type: string
          description: Human-readable error message
          example: "Sink URL must use HTTPS protocol"
        details:
          type: array
          items:
            type: string
          description: Additional details about the error
          example: ["Provided URL 'http://example.com' uses insecure HTTP protocol"]

  responses:
    BadRequest:
      description: Bad request - invalid parameters or syntax
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            invalidSink:
              summary: Invalid sink URL
              value:
                code: "INVALID_SINK_URL"
                message: "Sink URL must use HTTPS protocol"
                details: ["Provided URL 'http://example.com' uses insecure HTTP protocol"]

    Unauthorized:
      description: Unauthorized - missing or invalid authentication token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missingToken:
              summary: Missing authentication token
              value:
                code: "MISSING_AUTH_TOKEN"
                message: "Authentication token is required"

    Forbidden:
      description: Forbidden - insufficient permissions or quota exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            duplicateSubscription:
              summary: Duplicate subscription type
              value:
                code: "DUPLICATE_SUBSCRIPTION"
                message: "An active subscription for IMEI_CHANGE already exists"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            subscriptionNotFound:
              summary: Subscription not found
              value:
                code: "SUBSCRIPTION_NOT_FOUND"
                message: "Subscription with ID 'sub_invalid' does not exist"

    UnprocessableEntity:
      description: Unprocessable entity - semantic errors in request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    TooManyRequests:
      description: Too many requests - rate limit exceeded
      headers:
        Retry-After:
          description: Seconds to wait before retrying
          schema:
            type: integer
            example: 60
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        OAuth 2.0 Bearer token with 3-legged authorization flow.

        **Critical Requirements:**
        - Token MUST contain SIM identifier in claims (e.g., `phone_number` or `sim_id`)
        - 2-legged OAuth is NOT SUPPORTED
        - Token must have `iot-sim-fraud-prevention-subscription` scope
        - Token must be issued for the specific SIM being managed

        **Example token claims:**
        ```json
        {
          "sub": "user123",
          "phone_number": "+1234567890",
          "scope": "iot-sim-fraud-prevention-subscription",
          "exp": 1735689600
        }
        ```

security:
  - BearerAuth: []
