openapi: 3.0.3
info:
  title: IoT SIM Fraud Prevention API
  description: |
    This API provides fraud prevention capabilities for IoT SIM cards by allowing
    bindings of SIM cards to specific devices (via IMEI) or geographic areas.

    **Binding Types:**
    - **IMEI Binding**: Restricts SIM usage to a specific device identified by IMEI
    - **Area Binding**: Restricts SIM usage to a defined geographic area (circle-based)

    **How Bindings Work:**
    - Bindings are associated with the SIM card identified in the OAuth access token
    - When active, the network monitors SIM usage against the binding constraints
    - If SIM is used outside the bound device/area, fraud prevention mechanisms are triggered
    - For area bindings:
      * Area is defined as a circle with center (latitude/longitude) and radius (meters)
      * Location determination is based on cell tower data
      * If device moves outside the bound area, service may be restricted until verification
    - Only one active binding of each type (IMEI/area) is allowed per SIM at a time
    - Creating a new binding of the same type replaces the existing one

    **Authorization:**
    - 3-legged OAuth flow is REQUIRED (SIM identifier extracted from access token claims)
    - The access token MUST contain the SIM identifier (e.g., in `phone_number` or `sim_id` claim)
    - 2-legged OAuth is NOT SUPPORTED for privacy and security reasons
  version: 1.0.0
  contact:
    name: CAMARA API Support
    url: https://camara.org/support
    email: api-support@camara.org
  license:
    name: CAMARA API License
    url: https://camara.org/license

servers:
  - url: https://api.{environment}.camara.org/iot-sim-fraud-prevention/v1
    description: CAMARA IoT SIM Fraud Prevention API
    variables:
      environment:
        default: production
        enum:
          - sandbox
          - production
        description: Environment selector

paths:
  /bindings:
    post:
      summary: Create a new binding
      operationId: createBinding
      description: |
        Creates a new binding (IMEI or area) for the SIM card associated with the access token.

        **Behavior:**
        - If a binding of the same type already exists, it is replaced by the new binding
        - The new binding becomes active immediately
        - Response includes `Location` header with URI to the created binding resource
      tags:
        - Bindings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BindingCreateRequest'
            examples:
              imeiBinding:
                summary: Create IMEI binding
                value:
                  type: "IMEI"
                  bindingData:
                    imei: "356938035643809"
              areaBinding:
                summary: Create area binding
                value:
                  type: "AREA"
                  bindingData:
                    areaType: "CIRCLE"
                    center:
                      latitude: 40.7128
                      longitude: -74.006
                    radius: 5000
      responses:
        '201':
          description: Binding created successfully
          headers:
            Location:
              description: URI of the newly created binding resource
              schema:
                type: string
                format: uri
                example: /bindings/bnd_7a3f9c2e
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Binding'
              examples:
                imeiBindingCreated:
                  summary: IMEI binding created
                  value:
                    id: "bnd_7a3f9c2e"
                    type: "IMEI"
                    bindingData:
                      imei: "356938035643809"
                    createdAt: "2023-08-15T10:30:00Z"
                    updatedAt: "2023-08-15T10:30:00Z"
                areaBindingCreated:
                  summary: Area binding created
                  value:
                    id: "bnd_8b4d1a5f"
                    type: "AREA"
                    bindingData:
                      areaType: "CIRCLE"
                      center:
                        latitude: 40.7128
                        longitude: -74.006
                      radius: 5000
                    createdAt: "2023-08-15T10:30:00Z"
                    updatedAt: "2023-08-15T10:30:00Z"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'

    get:
      summary: List all bindings for the authenticated SIM
      operationId: listBindings
      description: |
        Retrieves all active bindings for the SIM card associated with the access token.

        **Filtering:**
        - Use `type` query parameter to filter by binding type (IMEI or AREA)
        - Omit parameter to retrieve all bindings
      tags:
        - Bindings
      parameters:
        - name: type
          in: query
          description: Filter bindings by type
          required: false
          schema:
            type: string
            enum: [IMEI, AREA]
          example: "IMEI"
      responses:
        '200':
          description: List of bindings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Binding'
              examples:
                allBindings:
                  summary: All bindings for SIM
                  value:
                    - id: "bnd_7a3f9c2e"
                      type: "IMEI"
                      bindingData:
                        imei: "356938035643809"
                      createdAt: "2023-08-15T10:30:00Z"
                      updatedAt: "2023-08-15T10:30:00Z"
                    - id: "bnd_8b4d1a5f"
                      type: "AREA"
                      bindingData:
                        areaType: "CIRCLE"
                        center:
                          latitude: 40.7128
                          longitude: -74.006
                        radius: 5000
                      createdAt: "2023-08-10T14:22:00Z"
                      updatedAt: "2023-08-10T14:22:00Z"
                imeiOnly:
                  summary: Only IMEI bindings
                  value:
                    - id: "bnd_7a3f9c2e"
                      type: "IMEI"
                      bindingData:
                        imei: "356938035643809"
                      createdAt: "2023-08-15T10:30:00Z"
                      updatedAt: "2023-08-15T10:30:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /bindings/{bindingId}:
    get:
      summary: Get binding details
      operationId: getBinding
      description: Retrieves details of a specific binding resource
      tags:
        - Bindings
      parameters:
        - name: bindingId
          in: path
          required: true
          description: Unique identifier of the binding resource
          schema:
            type: string
            pattern: '^bnd_[a-zA-Z0-9]{8,32}$'
          example: "bnd_7a3f9c2e"
      responses:
        '200':
          description: Binding details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Binding'
              examples:
                bindingDetails:
                  summary: Binding details
                  value:
                    id: "bnd_7a3f9c2e"
                    type: "IMEI"
                    bindingData:
                      imei: "356938035643809"
                    createdAt: "2023-08-15T10:30:00Z"
                    updatedAt: "2023-08-15T10:30:00Z"
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a binding
      operationId: deleteBinding
      description: |
        Deletes a binding resource, removing the restriction on SIM usage.

        **Important:**
        - After deletion, the SIM can be used on any device or in any area
        - This is a permanent deletion (resource will return 404 on subsequent GET)
        - No confirmation is required - deletion is immediate
      tags:
        - Bindings
      parameters:
        - name: bindingId
          in: path
          required: true
          description: Unique identifier of the binding to delete
          schema:
            type: string
            pattern: '^bnd_[a-zA-Z0-9]{8,32}$'
          example: "bnd_7a3f9c2e"
      responses:
        '204':
          description: Binding deleted successfully (no content)
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Binding:
      type: object
      required: [id, type, bindingData, createdAt, updatedAt]
      properties:
        id:
          type: string
          pattern: '^bnd_[a-zA-Z0-9]{8,32}$'
          description: Unique identifier for the binding resource
          example: "bnd_7a3f9c2e"
        type:
          type: string
          enum: [IMEI, AREA]
          description: Type of binding
          example: "IMEI"
        bindingData:
          description: Binding-specific data (discriminated by type field)
          oneOf:
            - $ref: '#/components/schemas/ImeiBindingData'
            - $ref: '#/components/schemas/AreaBindingData'
          discriminator:
            propertyName: type
            mapping:
              IMEI: '#/components/schemas/ImeiBindingData'
              AREA: '#/components/schemas/AreaBindingData'
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the binding was created (RFC 3339 format)
          example: "2023-08-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the binding was last updated (RFC 3339 format)
          example: "2023-08-15T10:30:00Z"
    
    BindingCreateRequest:
      type: object
      required: [type, bindingData]
      properties:
        type:
          type: string
          enum: [IMEI, AREA]
          description: Type of binding to create
        bindingData:
          description: Binding-specific data for creation
          oneOf:
            - $ref: '#/components/schemas/ImeiBindingData'
            - $ref: '#/components/schemas/AreaBindingData'
          discriminator:
            propertyName: type
            mapping:
              IMEI: '#/components/schemas/ImeiBindingData'
              AREA: '#/components/schemas/AreaBindingData'
    
    ImeiBindingData:
      type: object
      required: [imei]
      description: |
        IMEI binding restricts SIM usage to a specific device.
        
        **How it works:**
        - Network verifies the IMEI of the device using the SIM
        - If IMEI doesn't match the bound value, service is restricted
        - Ideal for fixed IoT devices (e.g., smart meters, asset trackers)
      properties:
        imei:
          type: string
          pattern: '^\d{15}$'
          description: IMEI number of the authorized device (15 digits)
          example: "356938035643809"
    
    AreaBindingData:
      type: object
      required: [areaType, center, radius]
      description: |
        Area binding restricts SIM usage to a defined geographic area.
        
        **How it works:**
        - Area is defined as a circle with center coordinates and radius
        - Network determines device location based on cell tower triangulation
        - If device moves outside the bound area, service may be restricted
        - Radius is measured in meters from the center point
        - Ideal for mobile IoT devices with expected operational areas (e.g., fleet vehicles, delivery drones)
      properties:
        areaType:
          type: string
          enum: [CIRCLE]
          description: Type of area geometry (currently only CIRCLE supported)
          example: "CIRCLE"
        center:
          $ref: '#/components/schemas/Point'
        radius:
          type: integer
          minimum: 100
          maximum: 200000
          description: Radius of the area in meters (100m to 200km)
          example: 5000
    
    Point:
      type: object
      required: [latitude, longitude]
      description: Geographic coordinate using WGS84 datum
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          description: Latitude coordinate in decimal degrees
          example: 40.7128
        longitude:
          type: number
          minimum: -180
          maximum: 180
          description: Longitude coordinate in decimal degrees
          example: -74.006
    
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          description: Machine-readable error code
          example: "INVALID_IMEI_FORMAT"
        message:
          type: string
          description: Human-readable error message
          example: "IMEI must be exactly 15 digits"
        details:
          type: array
          items:
            type: string
          description: Additional details about the error
          example: ["Provided IMEI '123' has invalid length"]
  
  responses:
    BadRequest:
      description: Bad request - invalid parameters or syntax
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            invalidImei:
              summary: Invalid IMEI format
              value:
                code: "INVALID_IMEI_FORMAT"
                message: "IMEI must be exactly 15 digits"
                details: ["Provided IMEI '123' has invalid length"]
    
    Unauthorized:
      description: Unauthorized - missing or invalid authentication token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missingToken:
              summary: Missing authentication token
              value:
                code: "MISSING_AUTH_TOKEN"
                message: "Authentication token is required"
    
    Forbidden:
      description: Forbidden - insufficient permissions or quota exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            quotaExceeded:
              summary: Rate limit exceeded
              value:
                code: "QUOTA_EXCEEDED"
                message: "Monthly binding creation quota exceeded"
    
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            bindingNotFound:
              summary: Binding not found
              value:
                code: "BINDING_NOT_FOUND"
                message: "Binding with ID 'bnd_invalid' does not exist"
    
    UnprocessableEntity:
      description: Unprocessable entity - semantic errors in request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            duplicateBinding:
              summary: Attempt to create duplicate binding type
              value:
                code: "DUPLICATE_BINDING_TYPE"
                message: "An active IMEI binding already exists for this SIM"
    
    TooManyRequests:
      description: Too many requests - rate limit exceeded
      headers:
        Retry-After:
          description: Seconds to wait before retrying
          schema:
            type: integer
            example: 60
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            rateLimit:
              summary: Rate limit exceeded
              value:
                code: "RATE_LIMIT_EXCEEDED"
                message: "Too many requests. Please retry after 60 seconds"
  
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        OAuth 2.0 Bearer token with 3-legged authorization flow.
        
        **Critical Requirements:**
        - Token MUST contain SIM identifier in claims (e.g., `phone_number` or `sim_id`)
        - 2-legged OAuth is NOT SUPPORTED
        - Token must have `iot-sim-fraud-prevention` scope
        - Token must be issued for the specific SIM being managed
        
        **Example token claims:**
        ```json
        {
          "sub": "user123",
          "phone_number": "+1234567890",
          "scope": "iot-sim-fraud-prevention",
          "exp": 1735689600
        }
        ```

security:
  - BearerAuth: []

